emulate sh -c 'source /etc/profile'

export EDITOR=vim
export VISUAL=$EDITOR
export PATH=$HOME/bin:$PATH
export MANPATH=$MANPATH:$HOME/share/man

# Some nicer colors for vim
export TERM=xterm-256color

# Prettier Java
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

# Default shell configuration
autoload -U compinit
compinit -C # We need -C, otherwise zsh complains about insecure includes

# Aliases
alias grep='grep --colour -n'

# Awesome "default" prompt
case ${UID} in
  0)
    PROMPT=$(print "\n%{[31m%}%n@%m%{[m%}: %{[33m%}%/\n%{[31m%}$%{[m%} ")
    SPROMPT="%r is correct? [n,y,a,e]: "
    ;;
  *)
    PROMPT=$(print "\n%{[35m%}%n@%m%{[m%}: %{[33m%}%/\n%{[35m%}$%{[m%} ")
    SPROMPT="%r is correct? [n,y,a,e]: "
    ;;
esac

# Options, a lot of options...
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt vi                  # vi-style commandline editing
setopt hist_ignore_dups    # ignore duplication command history list
setopt share_history       # share command history data
setopt correct
setopt nolistbeep
setopt auto_pushd
unsetopt globdots               # don't show hidden files in tab-completion
unsetopt auto_cd
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
zmodload -a regex
# Colors, colors colors COLORS!
setopt extendedglob
zmodload -a colors
zmodload -a autocomplete
zmodload -a complist
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# Show only as much as a window can handle in TAB - completion
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
# We want some typical behaviour for Ctrl-.. keys
bindkey '^P' history-beginning-search-backward-end
bindkey '^N' history-beginning-search-forward-end
bindkey '^?' backward-delete-char
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
# for "cancelling" tab completion
#bindkey list-prompt '^D' clear-screen

# ============ Colors for less ============ #
# Usefull LESS parameters:
# -e , for exit when reach end. -X to show the content in the shell, when exited (try it and you'll see)
export LESS="-r"
export LESS_TERMCAP_mb=$'\E[01;35m'
export LESS_TERMCAP_md=$'\E[01;35m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;42;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

